# Generated by Django 6.1 on 2026-08-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ammount',
            new_name='amount',
        ),
    ]
